### ISSUE TITLE
Organize code, stacks and data in memory

### ISSUE THREAD

**Issue by xbhatnag** [xbhatnag/XyOS#9]
Right now, all of physical memory is a huge mess. Code is plonked anywhere it fits. Stacks are created from arbitrary points in memory. This needs some order so that when we create a virtual memory model for EL0, things don't get too out of hand.

**Comment by xbhatnag** [comment]
Might even make EL1 operate in virtual memory. This needs some research. I remember this came up in my OS class. There were some benefits from doing so. Something about the kernel living in the second half of virtual memory which meant that data could be easily copied to and from the memory of the EL0 process?

**Comment by xbhatnag** [comment]
This requires understanding ARMs memory structure (physical and virtual) before proceeding.

**Comment by xbhatnag** [comment]
Alright. So I've been lazy. Really lazy. Mostly because virtual memory is hard.
Partly because "The Umbrella Academy" just came out on Netflix and I binged the whole damn thing over the weekend.

Water under the bridge.

**Comment by xbhatnag** [comment]
I'm reading the Virtual Memory chapter in the ARMv8 Architecture Reference Manual. It's really detailed. And they talk about a ton of stuff which I don't know if I need right now.

Switched to the Virtual Memory chapter in the ARMv8 Programmer's Guide which is way better to read and follow.

**Comment by xbhatnag** [comment]
From what I understand, each Exception Level has its own Virtual Memory system. EL1 and EL0 share a Virtual Memory system which can be programmed by EL1 or above.

This is perfect. I plan to use EL2 to setup a Virtual Memory system for EL1 and EL0. EL2 will keep living in physical memory. EL3 isn't implemented which means Security States are not a problem.

**Comment by xbhatnag** [comment]
I don't think there is a way around mapping the kernel to the second half of the virtual memory model. If the program needs to send information to the kernel for a syscall, how does it do that nicely? User programs and the kernel must exist in the same virtual memory space.

**Comment by xbhatnag** [comment]
It took really really long (because I was doing stupid stuff), but I think I have it working (kinda sorta).

**Comment by xbhatnag** [comment]
First problem : It is really hard to have one executable operate in physical and virtual memory space. The problem is that I'm sending binary files over serial instead of ELF files.

If I use the linker and create 2 address spaces for my executable, then the binary version becomes ~4GB because it fills the empty space between them with zeros.

So I needed to have 2 executables - a bootloader and a kernel.

**Comment by xbhatnag** [comment]
The bootloader operates in physical address space. It will download the kernel to a specific physical address. Then it performs all the virtual memory setup. Then it boots into the downloaded kernel.

**Comment by xbhatnag** [comment]
The virtual memory setup was the most annoying part in all of this.

I'm going with a 64KB page size. The 2 seconds of thought I put into this decision was basically that most programs are rarely 4KB in size and work with memory that is usually more than 4KB. So I want to avoid unnecessary extra paging.

**Comment by xbhatnag** [comment]
Since I will have the Kernel in the second half of virtual memory, I'm using AArch64's support for two VA ranges. Which means I will need to make 2x the page tables.

Pages & Tables need to be 64KB aligned in physical memory.
A 64KB granule means I have 3 levels of page tables - L1, L2 and L3.

An L1 Table can address ~280TB.
An L2 Table can address ~4TB.
An L3 Table can address ~512MB.

A 64bit virtual address uses the top 16 bits to identify which L1 table to use.
If the top 16 bits are all zero, the virtual address is from user space and the user space L1 table is used, otherwise it is from kernel space and the kernel space L1 table is used.

The remaining bits are addressed like so:
![screen shot 2019-02-24 at 12 33 31 pm](https://user-images.githubusercontent.com/14666061/53302801-6ffdcb00-3830-11e9-95a8-529f6fc06ee5.png)

**Comment by xbhatnag** [comment]
I started off by doing a 1:1 mapping between physical and virtual memory to see if things worked correctly. That helped iron out bugs with my page tables.

For some reason, when defining blocks in page tables, their recently-accessed bit must be set to 1, otherwise translations fail (!?!)

Also, the documentation wasn't clear about the bit pattern to use to identify when entries are valid. From what I read, the bit patterns were different when creating entries for tables vs for blocks. Turns out they're both the same.

**Comment by xbhatnag** [comment]
Once that was working, I tried to shoehorn the kernel into the second half of virtual memory.

I quickly realized that I couldn't do that. As explained before, it is difficult for the kernel to work in both physical and virtual space.

So I split the program into 2 parts. Bootloader and kernel.

**Comment by xbhatnag** [comment]
The Bootloader is loaded into memory by SerialClient, a lightweight executable on the SD Card of my Raspberry Pi that reads a program from serial, shoves it into memory and executes it.

**Comment by xbhatnag** [comment]
The Bootloader starts up in EL2 with the environment mostly unchanged. UART is setup because SerialClient needed it. But other than that, not much should have changed.

**Comment by xbhatnag** [comment]
Then I ran into a simple stupid bug.

The kernel address space was not working. The MMU refused to translate the start of kernel space (0xFFFF000000000000) and kept throwing Data aborts.

I checked everything - GitHub, Programmer Manuals, Technical Specifications, you name it.

It turns out that I was setting EL1 to 64-bit mode after setting up virtual memory, not before.

So my test translations (using the assembly instruction AT) kept failing because the MMU assumed that EL1 was in 32-bit mode.

It took 12 freaking hours to find this bug.

Man, I need a life...

**Comment by xbhatnag** [comment]
With that done, it was actually easy to get stuff working after. I needed space for the kernel EL1 stack and I needed space for peripherals.

Peripherals are at the end of virtual memory. They take 256 64KB pages. The kernel stack is given 1 64KB page and it starts right before the peripherals and grows to lower addresses.

**Comment by xbhatnag** [comment]
I've also neatened up the code quite a bit.
I've started having a directory structure.
Files now have more descriptive names.
Headers are a bit more consistent.
Using stdint.h a lot more for integer types.
Removing cruft from the code.

I've also done away with lower cases and underscores in filenames - I'm being nitpicky, but a lowercase filename with underscores looks kinda meh ("kern_load_asm.S" vs "KernelLoaderAssembly.S").

There's a ton of duplication and make is being particularly annoying right now.
I tried to move to CMake and promptly gave up. It tries to do too much for me.
And that doesn't work when you need to do bare-metal cross compiling.

I used a hack online that allows make to traverse subdirectories when looking for .c and .S files.
It isn't pretty and I need a change. That will happen soon.

I need to move a ton of duplicated code into a Libraries directory.
Part of me is tempted to use symlinks to solve this problem.

**Comment by xbhatnag** [comment]
And I think I broke the Mailbox code. It definitely doesn't work on virtual memory. I think the addresses that are supplied as data must be given from the GPU's perspective, so no virtual addresses. Might need to do some hacky ask-the-processor-for-the-physical-address or tell-el2-to-do-this-via-a-hypervisor-call. I haven't decided yet.

**Comment by xbhatnag** [comment]
Oh and the main event. Physical memory. How are things stored there?

Well, the SerialClient is put in the default kernel physical address (0x80000). SerialClient's stack is also at 0x80000 and grows to 0x0. This program won't live for long. This is fine.

I made arbitrary decisions about where to stick the bootloader (0xC0000) and kernel (0xE0000).
The bootloader's stack is also at 0xC0000 and grows to 0x0. That program isn't living for long either. This is also fine.

The page tables needed to start the kernel come immediately after the kernel code.
Immediately after that a page is taken for the kernel EL1 stack.

```
-------------------------
SerialClient Code + Stack
Bootloader Stack
-------------------------
Bootloader
-------------------------
Kernel
-------------------------
Kernel Page Tables
-------------------------
Kernel Stack
-------------------------
```

I'm trying to be as compact with this as possible.
I can see a future where SerialClient is merged into the Bootloader once I am confident about its capabilities.

**Comment by xbhatnag** [comment]
I can't think of anything else I did.

I probably need to figure out the GPU stuff and Library stuff later.

For now, my head hurts a bit. Going to the gym. I'll see if I'm in the mood to do some more when I come back.

**Comment by xbhatnag** [comment]
I also need to figure out how page maps and malloc fit in in this world...

**Comment by hacktheverse** [comment]
Don't forget to enable caching and inline functions and use macros wherever possible.

**Comment by xbhatnag** [comment]
The above recommendations belong in a separate issue. This is dealt with.
